### ISSUE TITLE
Zoom gesture detected as swipe on touch devices

### ISSUE THREAD

**Issue by dekatr0n** [emanuele-em/nuxt-swipe#1]
On touch devices, zooming using a multi-touch pinch gesture registers an unwanted swipe event. This is especially noticeable when zooming out.

**Comment by emanuele-em** [comment]
> On touch devices, zooming using a multi-touch pinch gesture registers an unwanted swipe event. This is especially noticeable when zooming out.

Thank you for the issue, I don't have time to solve it right now but feel free to send a PR 🙂
